class Item_Base_F;
class Launcher_Base_F;
class Pistol_Base_F;
class Weapon_Base_F;
class Weapon_Bag_Base;
class UAV_02_Base_lxWS;

class B_CTRG_Soldier_AR_tna_F;
class B_CTRG_Soldier_Exp_tna_F;
class B_AssaultPack_cbr;
class B_FieldPack_oli;
class B_Helipilot_F;
class B_FieldPack_khk;
class B_FieldPack_green_F;
class B_LegStrapBag_coyote_F;
class B_Kitbag_cbr;
class B_FieldPack_ocamo;
class B_recon_M_F;
class B_soldier_AR_F;
class B_soldier_M_F;
class B_soldier_UAV_F;
class B_soldier_repair_F;
class B_Soldier_GL_F;
class B_medic_F;
class I_C_Soldier_Bandit_1_F;
class I_C_Soldier_Bandit_2_F;
class I_C_Soldier_Bandit_4_F;
class I_C_Soldier_Para_2_F;
class I_G_medic_F;
class I_G_Soldier_exp_F;
class I_pilot_F;
class I_soldier_UAV_F;
class I_SFIA_scout_lxWS;
class I_SFIA_soldier_lxWS;
class I_SFIA_officer_lxWS;
class I_Soldier_AAA_F;
class I_Soldier_AAT_F;
class I_Soldier_AR_F;
class I_Soldier_AA_F;
class I_Soldier_AT_F;
class I_Soldier_repair_F;
class I_Tura_deserter_lxWS;
class O_crew_F;
class O_medic_F;
class O_SFIA_soldier_lxWS;
class O_Soldier_AR_F;
class O_Soldier_F;
class O_Soldier_GL_F;
class O_Soldier_LAT_F;
class O_Soldier_TL_F;
class O_soldier_UAV_F;

class NATO_Box_Base;
class SFIA_Box_Base_lxWS;

#include "\A3RO_CDLC_WS\CfgVehicles_Attachment_WS.hpp"
#include "\A3RO_CDLC_WS\CfgVehicles_Backpack_WS.hpp"
#include "\A3RO_CDLC_WS\CfgVehicles_DMR_WS.hpp"
#include "\A3RO_CDLC_WS\CfgVehicles_Faction_WS.hpp"
#include "\A3RO_CDLC_WS\CfgVehicles_Item_WS.hpp"
#include "\A3RO_CDLC_WS\CfgVehicles_Launcher_WS.hpp"
#include "\A3RO_CDLC_WS\CfgVehicles_MG_WS.hpp"
#include "\A3RO_CDLC_WS\CfgVehicles_Rifle_WS.hpp"